# Generated by Django 3.2.23 on 2023-11-19 15:21

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='activity_description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
