# Generated by Django 3.2.23 on 2023-11-21 20:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20231119_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
