# Generated by Django 4.2.7 on 2023-12-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_review_game_remove_review_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='game',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Save for later'), (1, 'Publish Now')], default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.game'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
