# Generated by Django 4.2.7 on 2023-12-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_gamecollection_gamecollectionitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
