# Generated by Django 4.2.7 on 2023-12-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_gamecollectionitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecollectionitem',
            options={'ordering': ['stage']},
        ),
        migrations.AlterUniqueTogether(
            name='gamecollectionitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gamecollectionitem',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Playing'), (1, 'Queued'), (2, 'Completed '), (3, 'Interested'), (4, 'Abandoned')], default='0'),
        ),
    ]
