# Generated by Django 4.2.7 on 2023-12-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='total_ratings',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
