# Generated by Django 4.2.7 on 2023-12-16 19:45

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_game_total_ratings_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='review',
            field=django_summernote.fields.SummernoteTextField(default=1, null=True),
        ),
    ]
