# Generated by Django 4.2.7 on 2023-12-16 19:46

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_game_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='review',
            field=django_summernote.fields.SummernoteTextField(default='', null=True),
        ),
    ]
